### ISSUE TITLE
Module fails to delete old logs on PowerShell 7.0.3 (on Raspberry Pi 4B) due to Sort alias

### ISSUE THREAD

**Issue by ghost** [dnwlf/PSSimpleLogging#1]
Hi, I get the following error using the module, (current v1.0.7178.18002), on my RasPi 4B:

```
Sort: /root/.local/share/powershell/Modules/PSSimpleLogging/1.0.7178.18002/PSSimpleLogging.psm1:127
Line |
 127 |          | Sort CreationTime | Select -First $RemoveLogsCount `
     |            ~~~~
     | The term 'Sort' is not recognized as the name of a cmdlet,
     | function, script file, or operable program. Check the spelling
     | of the name, or if a path was included, verify that the path
     | is correct and try again.
```

Expanding the alias to Sort-Object fixes the problem, (which was old logs not being deleted).

The Where alias, (i.l.o. Where-Object), is also used at line 115 and 126, they don't cause a problem but possibly expand them also?

**Comment by dnwlf** [comment]
I've updated the module to remove the aliases (now using Sort-Object, Where-Object, and Select-Object, rather than their aliases). Pushed the update to PowerShellGallery as 1.0.7541.14845. Please let me know if this update does not fix the issue.
